### ISSUE TITLE
Pas de version éditable COLORSQUARE de la feuille 2

### ISSUE THREAD

**Issue by elemay** [DHFTN/Feuille_Personnage_Square#1]
Comme dans le titre : pas de version éditable COLORSQUARE de la feuille 2 dans la release. Elle est dispo en version non éditable ou BLACKSQUARE.

Merci pour ce travail !

**Comment by HippoAndElephant** [comment]
Elle était bien présente mais avec une erreur de numérotation (elle portait le n°4 et non le n°2). Je viens de corriger tout cela.
Merci de m'avoir notifié cette erreur !
