### ISSUE TITLE
Le label "Cliquez pour ajouter une image" reste, même à l'impression

### ISSUE THREAD

**Issue by KyneSilverhide** [DHFTN/Feuille_Personnage_Square#2]
Bonjour,

Je ne suis pas certain qu'il ne s'agisse pas d'un bug dans Adobe ou autre (j'ai testé plusieurs logiciels), mais même à l'impression ou dans l'apercu, le etxte reste par dessus l'image...

![image](https://github.com/DHFTN/Feuille_Personnage_Square/assets/935348/d807afed-628c-4f66-b723-403cbd1ed551)

Ce n'est pas dramatique, mais c'est un peu dommage :)

**Comment by DHFTN** [comment]
Hello. Oui, il y avait un souci. Je viens de remettre à jour les fiches... Le libellé disparait totalement (même quand la fenêtre est vide) mais ça fonctionne toujours en cliquant dessus.

**Comment by KyneSilverhide** [comment]
Parfait ! ca marche, merci !

**Comment by DHFTN** [comment]
OK, je clôture.
